name: planti
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_splash_screen: ^1.0.4
  introduction_screen: ^3.1.14
  email_validator: ^3.0.0
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.5+3
  get: ^4.6.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/
    - assets/models/apple/
    - assets/models/corn/
    - assets/models/grape/
    - assets/models/potato/
    - assets/models/tomato/
